### ISSUE TITLE
Check in usd-sys bindings

### ISSUE THREAD

**Issue by Jasper-Bekkers** [vfx-rs/usd-bind#3]
Right now when doing a clean checkout of this repository and building the rust project you're faced with this error:

```cmd
error: failed to load manifest for workspace member `/home/jasper/vfx-rs/usd-bind/usd-rs/crates/usd`

Caused by:
  failed to load manifest for dependency `usd-cppstd`

Caused by:
  failed to load manifest for dependency `usd-sys`

Caused by:
  failed to read `/home/jasper/vfx-rs/usd-bind/build/usd-sys/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

For most of the Rust projects that we've maintained, we've checked in the `-sys` crate so that it's a lot easier for people to get up and running with the crate, and one can do a local checkout pretty easily without having to have a complex build environment.

Another implication of the way it's set up now, is that one can't easily patch the published crate with a local one through the `[patch.crates-io]` in Cargo.toml and quickly iterate / do fixes.

Usually what we do is we automate the process of generating the bindings through a simple Rust project that's manually invoked. Examples include https://github.com/MaikKlein/ash and https://github.com/gfx-rs/rspirv

**Comment by Jasper-Bekkers** [comment]
Would you accept a PR to make it more in line with conical rust build steps?

**Comment by luke-titley** [comment]
done
